=== JYWangGeneCosmo/Text-Edition-with-XSL-XSD-CSS-HTML/Textauszeichnung_TEDTalk_Rhetorics_JingyingWang.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" 
    targetNamespace="http://www.tei-c.org/ns/1.0" 
    xmlns:tei="http://www.tei-c.org/ns/1.0"
    xmlns:nonTei="http://www.tei-c.org/ns/1.0/nonTei/MyProject/JingyingWang"> 
    <xs:import namespace="http://www.tei-c.org/ns/1.0/nonTei/MyProject/JingyingWang" schemaLocation="nontei_TEDTalk_Rhetorics_JingyingWang.xsd"/> 
    <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/xml.xsd" />
    <xs:element name="TEI">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tei:teiHeader"/>
                <xs:element ref="tei:text"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="teiHeader">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tei:fileDesc"/>
                <xs:element ref="tei:encodingDesc"/>
                <xs:element ref="tei:profileDesc"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="fileDesc">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="titleStmt">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="respStmt">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="resp" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="publicationStmt">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="date" type="xs:date"/>
                            <xs:element ref="tei:p"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="sourceDesc">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="scriptStmt">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="title" type="xs:string"/>
                                        <xs:element name="speaker" type="xs:string"/>
                                        <!-- In der TED Talk Website gibt es keine Info über den genauen Tag der Rede. -->
                                        <xs:element name="date" type="xs:gYearMonth"></xs:element> 
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element> 
                        </xs:sequence>
                        <xs:attribute name="url" type="xs:anyURI"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="encodingDesc">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tei:p"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="profileDesc">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tei:p"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="p" type="xs:string"/>
    <xs:element name="l" type="xs:string"/>
    
    <xs:element name="segmentation">
        <xs:annotation>
            <xs:documentation>
                Die Segmentierung soll gleich wie die Segementierung des entsprechenden
                Transkripts auf der TEDTalk Webseite sein.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nonTei:sourceText"></xs:element>
                <xs:element ref="nonTei:translation"></xs:element>
            </xs:sequence>
            <xs:attribute name="n" type="xs:positiveInteger"></xs:attribute>
        </xs:complexType>
    </xs:element>   
                
                   
    <xs:element name="text">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="body">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="head" type="xs:string"/>
                            <xs:element ref="tei:segmentation" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
   
   
    <xs:element name="fs">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tei:f"/>
            </xs:sequence>
            <xs:attribute name="type" type = "xs:string" fixed = "rhetoric"/>
            <xs:attribute ref="xml:id">
                <xs:annotation>
                    <xs:documentation>
                        Für alle Sätze in &quot;sourceText&quot;, die rhetorische Mittel verwenden;
                        alle Sätze in &quot;translation&quot; die rhetorische Mittel verwenden, aber deren
                        entsprechende originale Sätze KEIN rhetorisches Mittel verwenden:
                        weisen jedem solchen Satz eine einzigartige ID zu.
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name ="ref" type="xs:IDREF">
                <xs:annotation>
                    <xs:documentation>
                        Jeder übersetzte Satz (in &quot;translation&quot;) für den Satz, der ein rhetorisches Mittel verwendet,
                        soll auf die ID des originale Satz referenziert werden (mit IDREF),
                        um das Alignment dazwischen zu erstellen.
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="f">
        <xs:complexType mixed="true">
            <xs:attribute name="name" use="required">  <!-- Rhetorisches Mittel muss genau spezifziert werden-->
                <xs:annotation>
                    <xs:documentation>
                        Für die Auszeichnung der rhetorischen Mittel werden Definitionen für 
                        die folgenden aufgezählten Rhetorik (außer &quot;selfMockery&quot;) in Wikipedia 
                        referenziert. Für &quot;selfMockery&quot; (Chleuasmos) wird die Definition für Chleuasmos 
                        in https://ifioque.com/figures-of-speech/trope/chleuasmos
                        order in &#187;A Dictionary of Literary Devices: Gradus, A-Z&#171; (Bernard Marie Dupriez, 1991) referenziert.
                    </xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base = "xs:string">
                        <xs:enumeration value = "metaphor"/>
                        <xs:enumeration value="selfMockery"/>
                        <xs:enumeration value = "parallelism"/>
                        <xs:enumeration value = "irony"/>
                        <xs:enumeration value="hyperbole"/>
                        <xs:enumeration value="NONE">
                            <xs:annotation>
                                <xs:documentation> 
                                    Falls das rhetorische Mittel nicht entsprechend in der Übersetzung
                                    representiert, dann wird der übersetzte Satz auch als &quot;fs&quot; 
                                    auf den originalen Satz referenzieren, aber dessen Attribut für den
                                    Name des rhetorischen Mittel soll &quot;NONE&quot; sein.
                                </xs:documentation>
                            </xs:annotation>
                        </xs:enumeration>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    
    

</xs:schema>

=== JYWangGeneCosmo/Text-Edition-with-XSL-XSD-CSS-HTML/Textauszeichnung_TEDTalk_Rhetorics_JingyingWang.xml
<?xml version="1.0" encoding="UTF-8"?>
<TEI xmlns="http://www.tei-c.org/ns/1.0"
    xmlns:nonTei="http://www.tei-c.org/ns/1.0/nonTei/MyProject/JingyingWang"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.tei-c.org/ns/1.0 Textauszeichnung_TEDTalk_Rhetorics_JingyingWang.xsd">
    <teiHeader>
        <fileDesc>
            <titleStmt>
                <title>Rhetorische Stilmittel in TED Talks</title>
                <respStmt>
                    <name>Jingying Wang</name>
                    <resp>Umwandlung in eine TEI-konforme Datei</resp>
                </respStmt>
            </titleStmt>
            <publicationStmt>
                <date>2020-03-27</date> 
                <p>Übungsprojekt für Textauszeichnung und Textkodierung</p>
            </publicationStmt>
            <sourceDesc url = "https://www.ted.com/talks/nora_mcinerny_we_don_t_move_on_from_grief_we_move_forward_with_it/transcript?referrer=playlist-the_most_popular_talks_of_2019#t-443338">
                <scriptStmt>
                    <title>We don&apos;t &quot;move on&quot; from grief. We move forward with it</title>
                    <speaker>Nora McInerny</speaker>
                    <date>2018-11</date>  <!-- gYearMonth -->
                </scriptStmt>
            </sourceDesc>
        </fileDesc>
        <encodingDesc>
            <p>
                Da es schon XML-Dateien für TED-Talk Transkriptionen gibt, 
                die Schwerpunkte für diese Auszeichnung liegen auf den rhetorischen Mitteln in dem ausgewählten TED Talk 
                und deren entsprechenden deutschen Übersetzungen. 
                Spezifisch gesagt werden Metapher, Ironie, Parallelismus, 
                Hyperbel (Übertreibung), Chleuasmos (self-mockery) diese 5 Typen von rhetorischen Mitteln 
                ausgezeichnet (Verwendete Definitionen für die rhetorische Mittel sehe bitte Dokumentation in der entsprechenden XSD-Datei).
                
                Verwendungsbereiche dieser Auszeichnung: 
                - Analyse der Übersetzungsstrategien (en-de) für bestimmte rhetorische Mittel 
                - Analyse der Verteilung oder Häufigkeit bestimmter rhetorischen Mittel in diesem Text
                - Unterstützung für die Erstellung der Trainingsdaten für manche NLP-Aufgaben wie z.B. Parallelismus-/ Metapher-Identifikation.
            </p>
        </encodingDesc>
        <profileDesc>
            <p>Dieses TED Talk über Liebe, Tod und Trauer hat zahlreiche Leute ermutigt und
                inspiriert. Diese Rede gehört zu &quot;The most popular talks of 2019&quot; und hat
                21 Übersetzungen. In dieser Rede werden vielfältige rhetorische Mittel 
                angewandt, die die Rede schöner und berührender macht. </p></profileDesc>
    </teiHeader>
    <text>
        <body>
            <head>We don&apos;t &quot;move on&quot; from grief. We move forward with it</head>
            <segmentation n="1">
                <nonTei:sourceText xml:lang="en">
                    <fs xml:id="rhe1.1"><f name="irony">So, 2014 was a big year for me. </f></fs>
                    <fs xml:id="rhe1.2"><f name="irony">Do you ever have that, just like a big year, like a banner year? </f></fs> 
                    <l>For me, it went like this: October 3, I lost my second
                    pregnancy. </l><l>And then October 8, my dad died of
                    cancer. </l><l>And then on November 25, my husband
                    Aaron died after three years with stage-four
                    glioblastoma, which is just a fancy word for brain
                    cancer. </l>
                </nonTei:sourceText>
                <nonTei:translation xml:lang="de">
                    <fs ref="rhe1.1"><f name="irony">2014 war ein tolles Jahr für mich. Kennen Sie so
                        etwas? </f></fs><fs ref="rhe1.2"><f name="irony">Einfach ein tolles Jahr, ein
                        Ausnahmejahr?</f></fs> <l>Für mich lief es so: Am 3. Oktober
                    verlor ich das zweite Kind durch einen Abgang. Am
                    8. Oktober starb mein Vater an Krebs und am 25.
                    November mein Mann Aaron nach 3 Jahren
                    Glioblastom im 4. Stadium, was einfach ein
                    schicker Name für einen Gehirntumor ist.</l></nonTei:translation>
            </segmentation>
            <segmentation n="2">
                <nonTei:sourceText xml:lang="en">
                    <fs xml:id="rhe2.1"><f name="selfMockery">So, I&apos;m fun.</f></fs>
                </nonTei:sourceText>
                <nonTei:translation xml:lang="de">
                    <fs ref="rhe2.1"><f name="selfMockery">Sie sehen, ich bin gut drauf.</f></fs>
                </nonTei:translation>
            </segmentation>
            <segmentation n="3">
                <nonTei:sourceText xml:lang="en">
                    <l>People love to invite me out all the time. </l>
                    <l>Packed social life. </l>
                    <l>Usually, when I talk about this period of my life, the reaction I get is essentially:</l>
                </nonTei:sourceText>
                <nonTei:translation xml:lang="de">
                    <l>Ich werde oft und gern eingeladen. </l>
                    <l>Das pralle soziale Leben. </l>
                    <l>Wenn ich über diese Zeit meines Leben spreche, reagieren die meisten immer so:</l>
                </nonTei:translation>
            </segmentation>
            <segmentation n="4">
                <nonTei:sourceText xml:lang="en">
                    <l>&quot;I can&apos;t -- I can&apos;t imagine.&quot; </l>
                    <l>But I do think you can. </l>
                    <fs xml:id="rhe4.1"><f name="parallelism">I think you can. And I think that you should </f></fs>
                    <l>because, someday, it&apos;s going to happen to you. </l>
                    <fs xml:id="rhe4.2"><f name="parallelism">Maybe not these specific losses in this specific order or at this speed, </f></fs>
                    <fs xml:id="rhe4.3"><f name="irony">
                        but like I said, I&apos;m very fun and the research
                        that I have seen will stun you: everyone you love
                        has a 100 percent chance of dying.</f>
                    </fs>
                </nonTei:sourceText>
                <nonTei:translation xml:lang="de">
                    <l>&quot;Das kann -- das kann ich mir nicht vorstellen.&quot; </l>
                    <l>Aber ich denke, Sie können das. </l>
                    <fs ref="rhe4.1"><f name="NONE">Sie schon. Das sollten Sie auch, </f></fs>
                    <l>weil es Ihnen auch passieren wird. </l>
                    <fs ref="rhe4.2"><f name="parallelism">Vielleicht nicht solche Verluste in
                        dieser Reihenfolge und diesem Tempo, </f></fs>
                    <fs ref="rhe4.3">
                        <f name="irony">aber wie gesagt, ich bin gut drauf und die
                            Forschungsergebnisse werden Sie überraschen: Jeder Mensch, 
                            den Sie lieben, wird hundertprozentig sterben.</f>
                    </fs>
                </nonTei:translation>
            </segmentation>
            <segmentation n="5">
                <nonTei:sourceText xml:lang="en">
                    <l>And that&apos;s why you came to TED.</l>
                </nonTei:sourceText>
                <nonTei:translation xml:lang="de">
                    <l>Deshalb sind Sie heute bei TED.</l>
                </nonTei:translation>
            </segmentation>
            <segmentation n="6">
                  <nonTei:sourceText xml:lang="en">
                      <l>So, since all of this loss happened, I&apos;ve made it a
                      career to talk about death and loss, not just my own, because it&apos;s pretty easy to recap, 
                      but the losses and tragedies that other people have experienced.</l>
                      <fs type ="rhetoric" xml:id="rhe6.1"><f name="selfMockery"> It&apos;s a niche, I have to say.</f></fs>
                  </nonTei:sourceText>
                  <nonTei:translation xml:lang="de">
                      <l>Wegen all meiner Verluste habe ich einen Beruf
                      daraus gemacht, über Tod und Verlust zu sprechen -- nicht nur über meine eigenen -- 
                      die sind schnell erzählt --, sondern über Verluste und Tragödien
                      anderer.</l>
                      <fs type ="rhetoric" ref="rhe6.1"><f name="selfMockery">Sagen wir mal, es ist ein Nische.</f></fs>
                  </nonTei:translation>
            </segmentation>
            <segmentation n="7">
                <nonTei:sourceText xml:lang="en">
                      <fs type ="rhetoric" xml:id="rhe7.1"><f name="selfMockery">It&apos;s a small niche, and I wish I made more money, but ...</f></fs>
                  </nonTei:sourceText>
                  <nonTei:translation xml:lang="de">
                      <fs type ="rhetoric" ref="rhe7.1"><f name="selfMockery">Eine kleine Nische und ich würde gern besser verdienen, aber --</f></fs>
                  </nonTei:translation>
              </segmentation>
            <segmentation n="8">
                <nonTei:sourceText xml:lang="en">
                      <fs type ="rhetoric" xml:id="rhe8.1"><f name ="parallelism">I&apos;ve written some very uplifting books, host a very
                        uplifting podcast, I started a little nonprofit.</f></fs> 
                      <l>I&apos;m just trying to do what I can to make more people
                        comfortable with the uncomfortable, and grief is so
                        uncomfortable.</l>
                      <l>It&apos;s so uncomfortable, especially if
                        it&apos;s someone else&apos;s grief. </l>
